// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoginPageWithError(errorMsg string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Login - EOG Alpaca Platform</title><link rel=\"stylesheet\" href=\"/static/css/output.css\"></head><body class=\"bg-gray-100 min-h-screen flex items-center justify-center\"><div class=\"bg-white rounded-xl shadow-lg p-8 max-w-md w-full\"><div class=\"text-center mb-8\"><svg class=\"h-16 w-16 mx-auto mb-4\" viewBox=\"0 0 100 100\"><path d=\"M50 5 C35 25 20 40 25 60 C28 75 35 85 50 95 C65 85 72 75 75 60 C80 40 65 25 50 5\" fill=\"#E31B23\"></path> <path d=\"M50 25 C42 38 35 48 38 60 C40 70 45 78 50 85 C55 78 60 70 62 60 C65 48 58 38 50 25\" fill=\"#FF6B6B\"></path> <ellipse cx=\"50\" cy=\"55\" rx=\"8\" ry=\"12\" fill=\"#FFD93D\"></ellipse></svg><h1 class=\"text-3xl font-bold text-gray-900 mb-2\">EOG ALPACA</h1><p class=\"text-gray-600\">Fantasy Trading Platform</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if errorMsg != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"mb-6 bg-red-50 border border-red-200 rounded-lg p-4\"><div class=\"flex items-start\"><svg class=\"w-5 h-5 text-red-500 mt-0.5 mr-3 flex-shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z\"></path></svg><div class=\"flex-1\"><p class=\"text-sm font-medium text-red-800\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(errorMsg)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/login_error.templ`, Line: 31, Col: 62}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<form method=\"POST\" action=\"/login\" class=\"space-y-4\"><p class=\"text-center text-gray-600 mb-6\">Enter your Alpaca API credentials to get started</p><div><label for=\"api_key\" class=\"block text-sm font-medium text-gray-700 mb-2\">API Key</label> <input type=\"text\" id=\"api_key\" name=\"api_key\" required class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-eog-red focus:border-transparent\" placeholder=\"PK...\"></div><div><label for=\"api_secret\" class=\"block text-sm font-medium text-gray-700 mb-2\">API Secret</label> <input type=\"password\" id=\"api_secret\" name=\"api_secret\" required class=\"w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-eog-red focus:border-transparent\" placeholder=\"Enter your API secret\"></div><button type=\"submit\" class=\"w-full bg-eog-red hover:bg-eog-dark-red text-white font-bold py-3 px-4 rounded-lg transition-colors\">Login</button><p class=\"text-xs text-gray-500 text-center mt-4\">Get your API keys from your Alpaca dashboard at <a href=\"https://app.alpaca.markets/paper/dashboard/overview\" target=\"_blank\" class=\"text-eog-red hover:underline\">alpaca.markets</a></p></form></div><style>\n\t\t\t\t.bg-eog-red {\n\t\t\t\t\tbackground-color: #E31B23;\n\t\t\t\t}\n\t\t\t\t.bg-eog-dark-red {\n\t\t\t\t\tbackground-color: #B91C1C;\n\t\t\t\t}\n\t\t\t</style></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
